# DecayCore
# Copyright (c) 2026 Vilho Valittu.
# All rights reserved except as expressly granted in the LICENSE file.
#
# This file is part of the public source-available DecayCore repository.
# Non-commercial use is permitted under the terms of the LICENSE file.
# Commercial use requires separate written permission.
#
# SPDX-License-Identifier: LicenseRef-DecayCore-Source-Available-NC-1.0

from __future__ import annotations

DEFAULT_MEASUREMENT_SAMPLE_RATE = 48000
DEFAULT_SWEEP_START_HZ = 1.0
DEFAULT_SWEEP_END_HZ = 24000.0
DEFAULT_SWEEP_LENGTH_S = 10.9
DEFAULT_PRE_SILENCE_S = 1.5
DEFAULT_POST_SILENCE_S = 0.5
DEFAULT_OUTPUT_GAIN_DB = -12.0
DEFAULT_MEASUREMENT_DITHER_LEVEL_DB = -90.0
DEFAULT_AUDIBILITY_TEST_DURATION_S = 3.0
DEFAULT_AUDIBILITY_TEST_GAIN_DB = -12.0
DEFAULT_AUDIBILITY_TEST_FADE_S = 0.02
DEFAULT_FADE_SAMPLES = 1000

DEFAULT_REFERENCE_CHIRP_START_HZ = 5000.0
DEFAULT_REFERENCE_CHIRP_END_HZ = 20000.0
DEFAULT_REFERENCE_CHIRP_DURATION_S = 0.1
DEFAULT_REFERENCE_CHIRP_GAP_S = 0.5
DEFAULT_REFERENCE_CHIRP_LEVEL_OFFSET_DB = 1.0


__all__ = [
    "DEFAULT_AUDIBILITY_TEST_DURATION_S",
    "DEFAULT_AUDIBILITY_TEST_FADE_S",
    "DEFAULT_AUDIBILITY_TEST_GAIN_DB",
    "DEFAULT_FADE_SAMPLES",
    "DEFAULT_MEASUREMENT_DITHER_LEVEL_DB",
    "DEFAULT_MEASUREMENT_SAMPLE_RATE",
    "DEFAULT_OUTPUT_GAIN_DB",
    "DEFAULT_POST_SILENCE_S",
    "DEFAULT_PRE_SILENCE_S",
    "DEFAULT_REFERENCE_CHIRP_DURATION_S",
    "DEFAULT_REFERENCE_CHIRP_END_HZ",
    "DEFAULT_REFERENCE_CHIRP_GAP_S",
    "DEFAULT_REFERENCE_CHIRP_LEVEL_OFFSET_DB",
    "DEFAULT_REFERENCE_CHIRP_START_HZ",
    "DEFAULT_SWEEP_END_HZ",
    "DEFAULT_SWEEP_LENGTH_S",
    "DEFAULT_SWEEP_START_HZ",
]
